### ISSUE TITLE
Repository purpose

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/datatype_definition#1]
I'm trying to understand the purpose of this repository and its relationship to all of the Bioschema groups. Is it to provide a common template that can be used in repositories for each of the different groups? That is, this repository will not contain any Bioschema specifications itself?

**Comment by guicalman** [comment]
Hi Alasdair, yes the purpose is to set up a markdown specification template for each Bioschemas type. The further work is to integrate them to the Bioschemas Web page  to have an up to date version of each Bioschemas data type.

**Comment by AlasdairGray** [comment]
Perhaps the title repository should be renamed to 'Specification Templates' and wherever you refer to 'Bioschemas Data Type' you say 'Bioschemas Specification'.

A specification could recommend the use of several schema.org/bioschema types. I would also avoid the use of Data so as not to get confused with the Data Repositories and Dataset specifications.

**Comment by agbeltran** [comment]
+1 for renaming - I think it makes things clearer

**Comment by guicalman** [comment]
Thank you very much Alasdair and Alejandra!

I made the changes taking your suggestions, for made it clear, we have to take into account that the specification is in building process, so it is subject to changes and suggestions.
